# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E_MANUAL_BOMUS',
            fields=[
                ('m_id', models.IntegerField(serialize=False, primary_key=True)),
                ('m_team', models.CharField(max_length=64)),
                ('m_patent_proposal', models.CharField(max_length=64)),
                ('m_patent_closure', models.CharField(max_length=64)),
                ('m_tax_deduction', models.CharField(max_length=64)),
                ('m_task_force', models.CharField(max_length=64)),
                ('m_exceed_expected', models.CharField(max_length=64)),
                ('m_idl', models.CharField(max_length=64)),
                ('m_gold', models.CharField(max_length=64)),
                ('m_datetime', models.DateTimeField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'e_manual_bomus',
            },
        ),
        migrations.CreateModel(
            name='EAttendance',
            fields=[
                ('a_id', models.IntegerField(serialize=False, primary_key=True)),
                ('a_datetime', models.DateField()),
                ('a_employee', models.CharField(max_length=32)),
                ('a_name', models.CharField(max_length=32)),
                ('a_leader', models.CharField(max_length=32)),
                ('a_team', models.CharField(max_length=100)),
                ('a_totalhours', models.IntegerField()),
                ('a_totaldays', models.IntegerField()),
                ('a_avghours', models.IntegerField()),
                ('a_maxhours', models.IntegerField()),
                ('a_totaloverhours', models.IntegerField()),
                ('a_avgoverhours', models.IntegerField()),
                ('a_maxoverhours', models.IntegerField()),
                ('a_totaldutyhours', models.IntegerField()),
                ('a_avgdutyhours', models.IntegerField()),
                ('a_maxdutyhours', models.IntegerField()),
                ('a_dutydays', models.IntegerField()),
                ('a_avglastcard', models.CharField(max_length=32)),
                ('a_maxlastcard', models.CharField(max_length=32)),
                ('a_nightnum', models.IntegerField()),
                ('a_offduty', models.IntegerField()),
                ('a_unoffduty', models.IntegerField()),
                ('a_eighttotal', models.IntegerField()),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'eattendance',
            },
        ),
        migrations.CreateModel(
            name='EATTENDANCEANOMALY',
            fields=[
                ('a_id', models.IntegerField(serialize=False, primary_key=True)),
                ('a_legal', models.CharField(max_length=64)),
                ('a_location', models.CharField(max_length=32)),
                ('a_bureau', models.CharField(max_length=64)),
                ('a_department', models.CharField(max_length=64)),
                ('a_class', models.CharField(max_length=64)),
                ('a_employeeid', models.CharField(max_length=32)),
                ('a_name', models.CharField(max_length=32)),
                ('a_datetime', models.DateField(null=True, blank=True)),
                ('a_datetype', models.CharField(max_length=32)),
                ('a_classcode', models.CharField(max_length=32)),
                ('a_type', models.CharField(max_length=64)),
                ('a_workcrad', models.CharField(max_length=32)),
                ('a_firstcrad', models.DateTimeField(null=True, blank=True)),
                ('a_anomalytype', models.CharField(max_length=32)),
                ('a_latetime', models.IntegerField(null=True, blank=True)),
                ('a_replytype', models.CharField(max_length=32)),
                ('a_closedcard', models.CharField(max_length=32)),
                ('a_lastcard', models.DateTimeField(null=True, blank=True)),
                ('a_anomalytype2', models.CharField(max_length=32)),
                ('a_earlytime', models.IntegerField(null=True, blank=True)),
                ('a_replytype2', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'eattendanceanomaly',
            },
        ),
        migrations.CreateModel(
            name='EBONUSDEPARTMENT',
            fields=[
                ('bd_id', models.IntegerField(serialize=False, primary_key=True)),
                ('bd_leader', models.CharField(max_length=100)),
                ('bd_hr', models.CharField(max_length=200)),
                ('bd_totalpercentage', models.CharField(max_length=200)),
                ('bd_totalmoney', models.FloatField()),
                ('bd_uuid', models.CharField(max_length=200)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
                ('bd_violation', models.FloatField()),
                ('bd_belowquality', models.FloatField()),
            ],
            options={
                'db_table': 'ebonusdepartment',
            },
        ),
        migrations.CreateModel(
            name='EBONUSPERCENTAGE',
            fields=[
                ('bp_id', models.IntegerField(serialize=False, primary_key=True)),
                ('bp_totalmoney', models.FloatField()),
                ('bp_personalmoney', models.FloatField()),
                ('bp_teammoney', models.FloatField()),
                ('bp_othermoney', models.FloatField()),
                ('bp_gsweight_t', models.FloatField()),
                ('bp_gsweight_d', models.FloatField()),
                ('bp_patentweight_t', models.FloatField()),
                ('bp_patentweight_d', models.FloatField()),
                ('bp_taxweight_t', models.FloatField()),
                ('bp_taxweight_d', models.FloatField()),
                ('bp_otherper_t', models.CharField(max_length=200)),
                ('bp_otherper_d', models.CharField(max_length=200)),
                ('bp_taskforceper_t', models.CharField(max_length=200)),
                ('bp_taskforceper_d', models.CharField(max_length=200)),
                ('bp_hrper_d', models.CharField(max_length=200)),
                ('bp_proposal_t', models.CharField(max_length=200)),
                ('bp_proposal_d', models.CharField(max_length=200)),
                ('bp_ee_t', models.CharField(max_length=200)),
                ('bp_ee_d', models.CharField(max_length=200)),
                ('bp_idl_t', models.CharField(max_length=200)),
                ('bp_idl_d', models.CharField(max_length=200)),
                ('bp_duty_t', models.CharField(max_length=200)),
                ('bp_duty_d', models.CharField(max_length=200)),
                ('bp_10_5_t', models.CharField(max_length=200)),
                ('bp_10_5_d', models.CharField(max_length=200)),
                ('bp_night_t', models.CharField(max_length=200)),
                ('bp_night_d', models.CharField(max_length=200)),
                ('bp_travel_abroad_t', models.CharField(max_length=200)),
                ('bp_travel_abroad_d', models.CharField(max_length=200)),
                ('bp_travel_cn_t', models.CharField(max_length=200)),
                ('bp_travel_cn_d', models.CharField(max_length=200)),
                ('bp_leave_t', models.CharField(max_length=200)),
                ('bp_leave_d', models.CharField(max_length=200)),
                ('bp_uuid', models.CharField(max_length=200)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'ebonuspercentage',
            },
        ),
        migrations.CreateModel(
            name='EBONUSREPORT',
            fields=[
                ('b_id', models.IntegerField(serialize=False, primary_key=True)),
                ('b_team', models.CharField(max_length=200)),
                ('b_leader', models.CharField(max_length=100)),
                ('b_teamleader', models.CharField(max_length=100)),
                ('b_hr', models.CharField(max_length=200)),
                ('b_gsnum', models.IntegerField()),
                ('b_gsweight', models.FloatField()),
                ('b_gsrate', models.CharField(max_length=200)),
                ('b_patent', models.IntegerField()),
                ('b_patentweight', models.FloatField()),
                ('b_patentrate', models.CharField(max_length=200)),
                ('b_tax', models.IntegerField()),
                ('b_taxweight', models.FloatField()),
                ('b_proposal', models.CharField(max_length=200)),
                ('b_ee', models.IntegerField()),
                ('b_eepoint', models.FloatField()),
                ('b_idl', models.IntegerField()),
                ('b_customer', models.CharField(max_length=200)),
                ('b_dutywork', models.FloatField()),
                ('b_dutyworkhc', models.FloatField()),
                ('b_over10_5', models.FloatField()),
                ('b_over10_5hc', models.FloatField()),
                ('b_night', models.FloatField()),
                ('b_nighthc', models.FloatField()),
                ('b_travelabroad', models.FloatField()),
                ('b_travelabroadhc', models.FloatField()),
                ('b_travelcn', models.FloatField()),
                ('b_travelcnhc', models.FloatField()),
                ('b_leaveprob', models.CharField(max_length=200)),
                ('b_leavepoint', models.FloatField()),
                ('b_leaverate', models.CharField(max_length=200)),
                ('b_attendance', models.CharField(max_length=200)),
                ('b_other', models.CharField(max_length=200)),
                ('b_taskforcenum', models.IntegerField()),
                ('b_taskforce', models.CharField(max_length=200)),
                ('b_total', models.CharField(max_length=200)),
                ('b_money', models.FloatField()),
                ('b_violation', models.FloatField()),
                ('b_belowquality', models.FloatField()),
                ('b_finalymoney', models.FloatField()),
                ('b_datetime', models.DateTimeField(null=True, blank=True)),
                ('b_tablename', models.CharField(max_length=200)),
                ('b_deldate', models.DateTimeField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
                ('b_uuid', models.CharField(max_length=200)),
                ('b_datatype', models.CharField(max_length=100)),
                ('b_teamloading', models.CharField(max_length=100)),
                ('b_totalpercentage_lastyear', models.CharField(max_length=100)),
                ('b_totalmoney_lastyear', models.FloatField()),
            ],
            options={
                'db_table': 'ebonusreport',
            },
        ),
        migrations.CreateModel(
            name='EBureau',
            fields=[
                ('b_id', models.IntegerField(serialize=False, primary_key=True)),
                ('b_bureau', models.CharField(unique=True, max_length=64)),
                ('b_leadernum', models.CharField(max_length=32)),
                ('b_leader', models.CharField(max_length=32)),
                ('b_up', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'ebureau',
            },
        ),
        migrations.CreateModel(
            name='EClasses',
            fields=[
                ('c_id', models.IntegerField(serialize=False, primary_key=True)),
                ('c_code', models.CharField(max_length=32)),
                ('c_type', models.CharField(max_length=32)),
                ('c_hours', models.IntegerField(null=True, blank=True)),
                ('c_firstup', models.CharField(max_length=32)),
                ('c_firstdown', models.CharField(max_length=32)),
                ('c_secondeup', models.CharField(max_length=32)),
                ('c_secondedown', models.CharField(max_length=32)),
                ('c_beginover', models.CharField(max_length=32)),
                ('c_description', models.CharField(max_length=256)),
                ('c_category', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'eclasses',
            },
        ),
        migrations.CreateModel(
            name='ECRD',
            fields=[
                ('c_id', models.IntegerField(serialize=False, primary_key=True)),
                ('c_legal', models.CharField(max_length=64)),
                ('c_plant', models.CharField(max_length=32)),
                ('c_datetime', models.DateField(null=True, blank=True)),
                ('c_datetype', models.CharField(max_length=32)),
                ('c_code', models.CharField(max_length=32)),
                ('c_type', models.CharField(max_length=32)),
                ('c_workcrad', models.CharField(max_length=32)),
                ('c_firstcrad', models.DateField(null=True, blank=True)),
                ('c_closedcard', models.CharField(max_length=32)),
                ('c_lastcard', models.DateField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'ecrd',
            },
        ),
        migrations.CreateModel(
            name='EDemand',
            fields=[
                ('d_id', models.IntegerField(serialize=False, primary_key=True)),
                ('d_urgency', models.CharField(max_length=32)),
                ('d_number', models.CharField(max_length=32)),
                ('d_status', models.CharField(max_length=32)),
                ('d_frequency', models.CharField(max_length=32)),
                ('d_bureau', models.CharField(max_length=64)),
                ('d_department', models.CharField(max_length=64)),
                ('d_abbreviation', models.CharField(max_length=32)),
                ('d_position', models.CharField(max_length=32)),
                ('d_amount', models.IntegerField(null=True, blank=True)),
                ('d_finished', models.IntegerField(null=True, blank=True)),
                ('d_offer', models.IntegerField(null=True, blank=True)),
                ('d_unfinish', models.IntegerField(null=True, blank=True)),
                ('d_requirement', models.IntegerField(null=True, blank=True)),
                ('d_experience', models.CharField(max_length=500)),
                ('d_recruiter', models.CharField(max_length=32)),
                ('d_grade', models.CharField(max_length=32)),
                ('d_cellphone', models.CharField(max_length=64)),
                ('d_degree', models.CharField(max_length=32)),
                ('d_working', models.CharField(max_length=32)),
                ('d_demand01', models.CharField(max_length=32)),
                ('d_demand02', models.CharField(max_length=32)),
                ('d_request', models.CharField(max_length=32)),
                ('d_require', models.CharField(max_length=500)),
                ('d_application', models.DateField(null=True, blank=True)),
                ('d_register', models.DateField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'edemand',
            },
        ),
        migrations.CreateModel(
            name='EDepartment',
            fields=[
                ('d_id', models.IntegerField(serialize=False, primary_key=True)),
                ('d_department', models.CharField(unique=True, max_length=64)),
                ('d_leadernum', models.CharField(max_length=32)),
                ('d_leader', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
                ('ebureau', models.ForeignKey(to='NPI_EERF.EBureau', null=True)),
            ],
            options={
                'db_table': 'edepartment',
            },
        ),
        migrations.CreateModel(
            name='EDeputy',
            fields=[
                ('d_id', models.IntegerField(serialize=False, primary_key=True)),
                ('d_character', models.CharField(max_length=32)),
                ('d_bureau', models.CharField(max_length=32)),
                ('d_department', models.CharField(max_length=32)),
                ('d_subject', models.CharField(max_length=32)),
                ('d_group', models.CharField(max_length=32)),
                ('d_line', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'edeputy',
            },
        ),
        migrations.CreateModel(
            name='EDimission',
            fields=[
                ('d_id', models.IntegerField(serialize=False, primary_key=True)),
                ('d_step', models.CharField(max_length=32)),
                ('d_number', models.CharField(max_length=32)),
                ('d_cname', models.CharField(max_length=32)),
                ('d_department', models.CharField(max_length=64)),
                ('d_grade', models.CharField(max_length=32)),
                ('d_management', models.CharField(max_length=32)),
                ('d_reason01', models.CharField(max_length=256)),
                ('d_reason02', models.CharField(max_length=256)),
                ('d_reason03', models.CharField(max_length=256)),
                ('d_firstdate', models.DateField(null=True, blank=True)),
                ('d_seniority', models.IntegerField(null=True, blank=True)),
                ('d_lastdate', models.DateField(null=True, blank=True)),
                ('d_requestdate', models.DateField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'edimission',
            },
        ),
        migrations.CreateModel(
            name='EDutywork',
            fields=[
                ('d_id', models.IntegerField(serialize=False, primary_key=True)),
                ('d_datetime', models.DateField(null=True, blank=True)),
                ('d_leader', models.CharField(max_length=32)),
                ('d_number', models.IntegerField(null=True, blank=True)),
                ('d_population', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'edutywork',
            },
        ),
        migrations.CreateModel(
            name='EEmployee',
            fields=[
                ('e_id', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('e_pwd', models.CharField(max_length=32)),
                ('e_cname', models.CharField(max_length=32)),
                ('e_grade', models.CharField(max_length=32)),
                ('e_direct', models.CharField(max_length=32)),
                ('e_difference', models.CharField(max_length=32)),
                ('e_management', models.CharField(max_length=32)),
                ('e_managers', models.CharField(max_length=32)),
                ('e_place', models.CharField(max_length=32)),
                ('e_DRI', models.CharField(max_length=32)),
                ('e_authority', models.CharField(max_length=32)),
                ('e_status', models.CharField(max_length=32)),
                ('e_lastdate', models.DateField(null=True, blank=True)),
                ('e_ename', models.CharField(max_length=32)),
                ('e_seniority', models.IntegerField(null=True, blank=True)),
                ('e_email', models.CharField(max_length=64)),
                ('e_phone', models.CharField(max_length=64)),
                ('e_cellphone', models.CharField(max_length=64)),
                ('e_cornet', models.CharField(max_length=32)),
                ('e_firstdate', models.DateField(null=True, blank=True)),
                ('e_degree', models.CharField(max_length=32)),
                ('e_leader', models.CharField(max_length=32)),
                ('e_functionteam', models.CharField(max_length=32)),
                ('e_category', models.CharField(max_length=32)),
                ('e_expiringdate', models.DateField(null=True, blank=True)),
                ('e_chmod', models.CharField(max_length=32)),
                ('e_adduser', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
                ('ebureau', models.ForeignKey(to='NPI_EERF.EBureau', null=True)),
                ('edepartment', models.ForeignKey(to='NPI_EERF.EDepartment', null=True)),
            ],
            options={
                'db_table': 'eemployee',
            },
        ),
        migrations.CreateModel(
            name='EGreaterthan',
            fields=[
                ('g_id', models.IntegerField(serialize=False, primary_key=True)),
                ('g_datetime', models.DateField(null=True, blank=True)),
                ('g_leader', models.CharField(max_length=32)),
                ('g_ontime', models.IntegerField(null=True, blank=True)),
                ('g_overtime', models.IntegerField(null=True, blank=True)),
                ('g_9_hours', models.IntegerField(null=True, blank=True)),
                ('g_9_5_hours', models.IntegerField(null=True, blank=True)),
                ('g_10_hours', models.IntegerField(null=True, blank=True)),
                ('g_10_5_hours', models.IntegerField(null=True, blank=True)),
                ('g_11_hours', models.IntegerField(null=True, blank=True)),
                ('g_11_5_hours', models.IntegerField(null=True, blank=True)),
                ('g_12_hours', models.IntegerField(null=True, blank=True)),
                ('g_12_5_hours', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'egreaterthan',
            },
        ),
        migrations.CreateModel(
            name='EGroup',
            fields=[
                ('g_id', models.IntegerField(serialize=False, primary_key=True)),
                ('g_group', models.CharField(max_length=64)),
                ('g_leadernum', models.CharField(max_length=32)),
                ('g_leader', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'egroup',
            },
        ),
        migrations.CreateModel(
            name='EGSPBYLEADER',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('e_leader', models.CharField(max_length=200)),
                ('e_functionteam', models.CharField(max_length=200)),
                ('e_closed_num', models.IntegerField()),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
                ('e_year', models.CharField(max_length=200)),
                ('e_team_target', models.IntegerField()),
                ('e_performance', models.IntegerField()),
                ('e_no_closed_num', models.IntegerField()),
                ('e_register_num', models.IntegerField()),
                ('e_team_hc', models.IntegerField()),
                ('e_per_benefit', models.IntegerField()),
            ],
            options={
                'db_table': 'egspbyleader',
            },
        ),
        migrations.CreateModel(
            name='EHumans',
            fields=[
                ('h_id', models.IntegerField(serialize=False, primary_key=True)),
                ('h_cname', models.CharField(max_length=32)),
                ('h_num', models.CharField(max_length=32)),
                ('h_ename', models.CharField(max_length=32)),
                ('h_group', models.CharField(max_length=32)),
                ('h_team', models.CharField(unique=True, max_length=32)),
                ('h_taiwan', models.IntegerField(null=True, blank=True)),
                ('h_mesome', models.IntegerField(null=True, blank=True)),
                ('h_technician', models.IntegerField(null=True, blank=True)),
                ('h_spindrift', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'ehumans',
            },
        ),
        migrations.CreateModel(
            name='ELateMealFee',
            fields=[
                ('l_id', models.IntegerField(serialize=False, primary_key=True)),
                ('l_datetime', models.DateField(null=True, blank=True)),
                ('l_employee', models.CharField(max_length=32)),
                ('l_cname', models.CharField(max_length=32)),
                ('l_leader', models.CharField(max_length=32)),
                ('l_interval', models.CharField(max_length=32)),
                ('l_weeknum', models.IntegerField(null=True, blank=True)),
                ('l_eightlate', models.IntegerField(null=True, blank=True)),
                ('l_ninelate', models.IntegerField(null=True, blank=True)),
                ('l_tenlate', models.IntegerField(null=True, blank=True)),
                ('l_elevenlate', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'elatemealfee',
            },
        ),
        migrations.CreateModel(
            name='ELeader',
            fields=[
                ('l_id', models.IntegerField(serialize=False, primary_key=True)),
                ('l_leadernum', models.CharField(unique=True, max_length=32)),
                ('l_leader', models.CharField(max_length=32)),
                ('l_group', models.CharField(max_length=32)),
                ('edepartment_num', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
                ('edepartment', models.ForeignKey(to='NPI_EERF.EDepartment', null=True)),
            ],
            options={
                'db_table': 'eleader',
            },
        ),
        migrations.CreateModel(
            name='Eleavenum',
            fields=[
                ('l_id', models.IntegerField(serialize=False, primary_key=True)),
                ('l_datetime', models.DateField(null=True, blank=True)),
                ('l_leader', models.CharField(max_length=32)),
                ('l_leavenum', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'eleavenum',
            },
        ),
        migrations.CreateModel(
            name='Eleaveprob',
            fields=[
                ('l_id', models.IntegerField(serialize=False, primary_key=True)),
                ('l_datetime', models.DateField(null=True, blank=True)),
                ('l_leaveprob', models.FloatField()),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'eleaveprob',
            },
        ),
        migrations.CreateModel(
            name='ELine',
            fields=[
                ('l_id', models.IntegerField(serialize=False, primary_key=True)),
                ('l_group', models.CharField(max_length=64)),
                ('l_leadernum', models.CharField(max_length=32)),
                ('l_leader', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
                ('egroup', models.ForeignKey(to='NPI_EERF.EGroup', null=True)),
            ],
            options={
                'db_table': 'eline',
            },
        ),
        migrations.CreateModel(
            name='ELMFAttendance',
            fields=[
                ('a_id', models.IntegerField(serialize=False, primary_key=True)),
                ('a_datetime', models.DateField()),
                ('a_employee', models.CharField(max_length=32)),
                ('a_name', models.CharField(max_length=32)),
                ('a_leader', models.CharField(max_length=32)),
                ('a_team', models.CharField(max_length=100)),
                ('a_totalhours', models.IntegerField()),
                ('a_totaldays', models.IntegerField()),
                ('a_avghours', models.IntegerField()),
                ('a_maxhours', models.IntegerField()),
                ('a_totaloverhours', models.IntegerField()),
                ('a_avgoverhours', models.IntegerField()),
                ('a_maxoverhours', models.IntegerField()),
                ('a_totaldutyhours', models.IntegerField()),
                ('a_avgdutyhours', models.IntegerField()),
                ('a_maxdutyhours', models.IntegerField()),
                ('a_dutydays', models.IntegerField()),
                ('a_avglastcard', models.CharField(max_length=32)),
                ('a_maxlastcard', models.CharField(max_length=32)),
                ('a_nightnum', models.IntegerField()),
                ('a_offduty', models.IntegerField()),
                ('a_unoffduty', models.IntegerField()),
                ('a_eightlate', models.IntegerField()),
                ('a_eighttotal', models.IntegerField()),
                ('a_tenlate', models.IntegerField()),
                ('a_interval', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'elmfattendance',
            },
        ),
        migrations.CreateModel(
            name='ELMFPersonalWorkTime',
            fields=[
                ('p_id', models.IntegerField(serialize=False, primary_key=True)),
                ('p_datetime', models.DateField(null=True, blank=True)),
                ('p_leader', models.CharField(max_length=32)),
                ('p_employee', models.CharField(max_length=32)),
                ('p_9_hours', models.IntegerField(null=True, blank=True)),
                ('p_9_5_hours', models.IntegerField(null=True, blank=True)),
                ('p_10_hours', models.IntegerField(null=True, blank=True)),
                ('p_10_5_hours', models.IntegerField(null=True, blank=True)),
                ('p_11_hours', models.IntegerField(null=True, blank=True)),
                ('p_11_5_hours', models.IntegerField(null=True, blank=True)),
                ('p_12_hours', models.IntegerField(null=True, blank=True)),
                ('p_12_5_hours', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'elmfpersonalworktime',
            },
        ),
        migrations.CreateModel(
            name='ENightshift',
            fields=[
                ('n_id', models.IntegerField(serialize=False, primary_key=True)),
                ('n_datetime', models.DateField(null=True, blank=True)),
                ('n_leader', models.CharField(max_length=32)),
                ('n_number', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'enightshift',
            },
        ),
        migrations.CreateModel(
            name='EOverhours',
            fields=[
                ('h_id', models.IntegerField(serialize=False, primary_key=True)),
                ('h_place', models.CharField(max_length=32)),
                ('h_department', models.CharField(max_length=64)),
                ('h_grade', models.CharField(max_length=32)),
                ('h_type', models.CharField(max_length=32)),
                ('h_yearmouth', models.DateField(null=True, blank=True)),
                ('h_01', models.IntegerField(null=True, blank=True)),
                ('h_02', models.IntegerField(null=True, blank=True)),
                ('h_03', models.IntegerField(null=True, blank=True)),
                ('h_04', models.IntegerField(null=True, blank=True)),
                ('h_05', models.IntegerField(null=True, blank=True)),
                ('h_06', models.IntegerField(null=True, blank=True)),
                ('h_07', models.IntegerField(null=True, blank=True)),
                ('h_08', models.IntegerField(null=True, blank=True)),
                ('h_09', models.IntegerField(null=True, blank=True)),
                ('h_10', models.IntegerField(null=True, blank=True)),
                ('h_11', models.IntegerField(null=True, blank=True)),
                ('h_12', models.IntegerField(null=True, blank=True)),
                ('h_13', models.IntegerField(null=True, blank=True)),
                ('h_14', models.IntegerField(null=True, blank=True)),
                ('h_15', models.IntegerField(null=True, blank=True)),
                ('h_16', models.IntegerField(null=True, blank=True)),
                ('h_17', models.IntegerField(null=True, blank=True)),
                ('h_18', models.IntegerField(null=True, blank=True)),
                ('h_19', models.IntegerField(null=True, blank=True)),
                ('h_20', models.IntegerField(null=True, blank=True)),
                ('h_21', models.IntegerField(null=True, blank=True)),
                ('h_22', models.IntegerField(null=True, blank=True)),
                ('h_23', models.IntegerField(null=True, blank=True)),
                ('h_24', models.IntegerField(null=True, blank=True)),
                ('h_25', models.IntegerField(null=True, blank=True)),
                ('h_26', models.IntegerField(null=True, blank=True)),
                ('h_27', models.IntegerField(null=True, blank=True)),
                ('h_28', models.IntegerField(null=True, blank=True)),
                ('h_29', models.IntegerField(null=True, blank=True)),
                ('h_30', models.IntegerField(null=True, blank=True)),
                ('h_31', models.IntegerField(null=True, blank=True)),
                ('h_32', models.IntegerField(null=True, blank=True)),
                ('h_33', models.IntegerField(null=True, blank=True)),
                ('h_34', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
                ('eemployee', models.ForeignKey(to='NPI_EERF.EEmployee', null=True)),
            ],
            options={
                'db_table': 'eoverhours',
            },
        ),
        migrations.CreateModel(
            name='EPersonalWorkTime',
            fields=[
                ('p_id', models.IntegerField(serialize=False, primary_key=True)),
                ('p_datetime', models.DateField(null=True, blank=True)),
                ('p_leader', models.CharField(max_length=32)),
                ('p_employee', models.CharField(max_length=32)),
                ('p_9_hours', models.IntegerField(null=True, blank=True)),
                ('p_9_5_hours', models.IntegerField(null=True, blank=True)),
                ('p_10_hours', models.IntegerField(null=True, blank=True)),
                ('p_10_5_hours', models.IntegerField(null=True, blank=True)),
                ('p_11_hours', models.IntegerField(null=True, blank=True)),
                ('p_11_5_hours', models.IntegerField(null=True, blank=True)),
                ('p_12_hours', models.IntegerField(null=True, blank=True)),
                ('p_12_5_hours', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'epersonalworktime',
            },
        ),
        migrations.CreateModel(
            name='EProvide',
            fields=[
                ('p_id', models.IntegerField(serialize=False, primary_key=True)),
                ('p_engineers', models.IntegerField(null=True, blank=True)),
                ('p_technician', models.IntegerField(null=True, blank=True)),
                ('p_yeardate', models.DateField(null=True, blank=True)),
                ('p_leader', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'eprovide',
            },
        ),
        migrations.CreateModel(
            name='ERecruit',
            fields=[
                ('r_id', models.IntegerField(serialize=False, primary_key=True)),
                ('r_status', models.CharField(max_length=32)),
                ('r_number', models.CharField(max_length=32)),
                ('r_name', models.CharField(max_length=32)),
                ('r_sex', models.CharField(max_length=32)),
                ('r_Idcard', models.CharField(max_length=32)),
                ('r_contact', models.CharField(max_length=32)),
                ('r_interview', models.DateField(null=True, blank=True)),
                ('r_bureau', models.CharField(max_length=64)),
                ('r_department', models.CharField(max_length=64)),
                ('r_position', models.CharField(max_length=32)),
                ('r_demand01', models.CharField(max_length=32)),
                ('r_demand02', models.CharField(max_length=32)),
                ('r_source', models.CharField(max_length=32)),
                ('r_recruiter', models.CharField(max_length=32)),
                ('r_degree', models.CharField(max_length=32)),
                ('r_grade', models.CharField(max_length=32)),
                ('r_result01', models.CharField(max_length=32)),
                ('r_result02', models.CharField(max_length=32)),
                ('r_progress', models.CharField(max_length=32)),
                ('r_healthcheck', models.DateField(null=True, blank=True)),
                ('r_checkresult', models.CharField(max_length=32)),
                ('r_register', models.DateField(null=True, blank=True)),
                ('r_anomaly', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'erecruit',
            },
        ),
        migrations.CreateModel(
            name='ERest',
            fields=[
                ('r_id', models.IntegerField(serialize=False, primary_key=True)),
                ('r_datetime', models.DateField(null=True, blank=True)),
                ('r_employee', models.CharField(max_length=32)),
                ('r_effectivity01', models.IntegerField(null=True, blank=True)),
                ('r_overtime01', models.IntegerField(null=True, blank=True)),
                ('r_rest01', models.IntegerField(null=True, blank=True)),
                ('r_effectivity02', models.IntegerField(null=True, blank=True)),
                ('r_overtime02', models.IntegerField(null=True, blank=True)),
                ('r_rest02', models.IntegerField(null=True, blank=True)),
                ('r_effectivity03', models.IntegerField(null=True, blank=True)),
                ('r_nightshift', models.IntegerField(null=True, blank=True)),
                ('r_totalrest', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'erest',
            },
        ),
        migrations.CreateModel(
            name='ESectionDutywork',
            fields=[
                ('d_id', models.IntegerField(serialize=False, primary_key=True)),
                ('d_datetime', models.DateField(null=True, blank=True)),
                ('d_section', models.CharField(max_length=32)),
                ('d_number', models.IntegerField(null=True, blank=True)),
                ('d_population', models.IntegerField(null=True, blank=True)),
                ('d_leader', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'esectiondutywork',
            },
        ),
        migrations.CreateModel(
            name='ESectionGreaterthan',
            fields=[
                ('g_id', models.IntegerField(serialize=False, primary_key=True)),
                ('g_datetime', models.DateField(null=True, blank=True)),
                ('g_section', models.CharField(max_length=32)),
                ('g_ontime', models.IntegerField(null=True, blank=True)),
                ('g_overtime', models.IntegerField(null=True, blank=True)),
                ('g_9_hours', models.IntegerField(null=True, blank=True)),
                ('g_9_5_hours', models.IntegerField(null=True, blank=True)),
                ('g_10_hours', models.IntegerField(null=True, blank=True)),
                ('g_10_5_hours', models.IntegerField(null=True, blank=True)),
                ('g_11_hours', models.IntegerField(null=True, blank=True)),
                ('g_11_5_hours', models.IntegerField(null=True, blank=True)),
                ('g_12_hours', models.IntegerField(null=True, blank=True)),
                ('g_12_5_hours', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'esectiongreaterthan',
            },
        ),
        migrations.CreateModel(
            name='ESectionNightshift',
            fields=[
                ('n_id', models.IntegerField(serialize=False, primary_key=True)),
                ('n_datetime', models.DateField(null=True, blank=True)),
                ('n_section', models.CharField(max_length=32)),
                ('n_number', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'esectionnightshift',
            },
        ),
        migrations.CreateModel(
            name='ESectionTimeout',
            fields=[
                ('t_id', models.IntegerField(serialize=False, primary_key=True)),
                ('t_datetime', models.DateField(null=True, blank=True)),
                ('t_section', models.CharField(max_length=32)),
                ('t_over9', models.IntegerField(null=True, blank=True)),
                ('t_over95', models.IntegerField(null=True, blank=True)),
                ('t_over10', models.IntegerField(null=True, blank=True)),
                ('t_over105', models.IntegerField(null=True, blank=True)),
                ('t_over11', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'esectiontimeout',
            },
        ),
        migrations.CreateModel(
            name='ESubject',
            fields=[
                ('s_id', models.IntegerField(serialize=False, primary_key=True)),
                ('s_subject', models.CharField(unique=True, max_length=64)),
                ('s_leadernum', models.CharField(max_length=32)),
                ('s_leader', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
                ('edepartment', models.ForeignKey(to='NPI_EERF.EDepartment', null=True)),
            ],
            options={
                'db_table': 'esubject',
            },
        ),
        migrations.CreateModel(
            name='ESubjectTeam',
            fields=[
                ('st_id', models.IntegerField(serialize=False, primary_key=True)),
                ('st_subject', models.CharField(unique=True, max_length=64)),
                ('st_team', models.CharField(max_length=32)),
                ('st_place', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'esubjectteam',
            },
        ),
        migrations.CreateModel(
            name='ETeam',
            fields=[
                ('t_id', models.IntegerField(serialize=False, primary_key=True)),
                ('t_team', models.CharField(unique=True, max_length=32)),
                ('t_place', models.CharField(max_length=32)),
                ('t_leader', models.CharField(max_length=100)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
                ('t_subject_leader', models.CharField(max_length=100)),
                ('eleader', models.ForeignKey(to='NPI_EERF.ELeader', null=True)),
            ],
            options={
                'db_table': 'eteam',
            },
        ),
        migrations.CreateModel(
            name='ETimeout',
            fields=[
                ('t_id', models.IntegerField(serialize=False, primary_key=True)),
                ('t_datetime', models.DateField(null=True, blank=True)),
                ('t_leader', models.CharField(max_length=32)),
                ('t_over9', models.IntegerField(null=True, blank=True)),
                ('t_over95', models.IntegerField(null=True, blank=True)),
                ('t_over10', models.IntegerField(null=True, blank=True)),
                ('t_over105', models.IntegerField(null=True, blank=True)),
                ('t_over11', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'etimeout',
            },
        ),
        migrations.CreateModel(
            name='ETotalmans',
            fields=[
                ('t_id', models.IntegerField(serialize=False, primary_key=True)),
                ('t_datetime', models.DateField(null=True, blank=True)),
                ('t_headcount', models.IntegerField(null=True, blank=True)),
                ('t_reserve', models.IntegerField(null=True, blank=True)),
                ('t_leave', models.IntegerField(null=True, blank=True)),
                ('t_engineers', models.IntegerField(null=True, blank=True)),
                ('t_technician', models.IntegerField(null=True, blank=True)),
                ('t_supporter', models.IntegerField(null=True, blank=True)),
                ('t_loan', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'etotalmans',
            },
        ),
        migrations.CreateModel(
            name='ETRAVELCOUNT',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('t_leader', models.CharField(max_length=200)),
                ('t_functionteam', models.CharField(max_length=200)),
                ('t_type', models.CharField(max_length=200)),
                ('t_count', models.IntegerField()),
                ('t_datetime', models.DateField(null=True, blank=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('edit_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'etravelcount',
            },
        ),
        migrations.AddField(
            model_name='eprovide',
            name='eteam',
            field=models.ForeignKey(to='NPI_EERF.ETeam', null=True),
        ),
        migrations.AddField(
            model_name='egroup',
            name='esubject',
            field=models.ForeignKey(to='NPI_EERF.ESubject', null=True),
        ),
        migrations.AddField(
            model_name='eemployee',
            name='egroup',
            field=models.ForeignKey(to='NPI_EERF.EGroup', null=True),
        ),
        migrations.AddField(
            model_name='eemployee',
            name='eline',
            field=models.ForeignKey(to='NPI_EERF.ELine', null=True),
        ),
        migrations.AddField(
            model_name='eemployee',
            name='esubject',
            field=models.ForeignKey(to='NPI_EERF.ESubject', null=True),
        ),
        migrations.AddField(
            model_name='edeputy',
            name='eemployee',
            field=models.ForeignKey(to='NPI_EERF.EEmployee', null=True),
        ),
        migrations.AddField(
            model_name='ecrd',
            name='eemployee',
            field=models.ForeignKey(to='NPI_EERF.EEmployee', null=True),
        ),
    ]
